# frozen_string_literal: true

require "spec_helper"

describe IsbnValidator do
  subject do
    Class.new do
      include ActiveModel::Validations
      attr_accessor :isbn
      validates :isbn, isbn: true, allow_blank: true

      def self.name
        "TestModel"
      end
    end.new
  end

  context "ISBN-13 validation" do
    it "allows valid ISBN-13 generated by Faker" do
      10.times do
        subject.isbn = Faker::Code.isbn
        expect(subject).to be_valid, "Expected #{subject.isbn} to be valid, but got errors: #{subject.errors.full_messages}"
      end
    end

    it "allows valid ISBN-13 with hyphens starting with 978" do
      subject.isbn = "978-0-13-235088-4"
      expect(subject).to be_valid
    end

    it "allows valid ISBN-13 with hyphens starting with 979" do
      subject.isbn = "979-8-89170-497-8"
      expect(subject).to be_valid
    end

    it "allows valid ISBN-13 without hyphens" do
      subject.isbn = "9780132350884"
      expect(subject).to be_valid
    end

    it "allows ISBN-13 with spaces" do
      subject.isbn = "978 0 13 235088 4"
      expect(subject).to be_valid
    end

    it "rejects ISBN-13 with invalid checksum" do
      subject.isbn = "978-0-13-235088-5"
      expect(subject).not_to be_valid
      expect(subject.errors[:isbn]).to include "doesn't appear to be a valid ISBN. Please check the number and try again"
    end

    it "rejects ISBN-13 not starting with 978 or 979" do
      subject.isbn = "9770132350884"
      expect(subject).not_to be_valid
      expect(subject.errors[:isbn]).to include "must start with 978 or 979 for ISBN-13 format"
    end
  end

  context "ISBN-10 validation" do
    it "allows valid ISBN-10 generated by Faker" do
      10.times do
        subject.isbn = Faker::Code.isbn(base: 10)
        expect(subject).to be_valid, "Expected #{subject.isbn} to be valid, but got errors: #{subject.errors.full_messages}"
      end
    end

    it "allows valid ISBN-10 with hyphens" do
      subject.isbn = "0-13-235088-2"
      expect(subject).to be_valid
    end

    it "allows valid ISBN-10 without hyphens" do
      subject.isbn = "0132350882"
      expect(subject).to be_valid
    end

    it "allows valid ISBN-10 with X check digit" do
      subject.isbn = "043942089X"
      expect(subject).to be_valid
    end

    it "allows ISBN-10 with lowercase x check digit" do
      subject.isbn = "043942089x"
      expect(subject).to be_valid
    end

    it "rejects ISBN-10 with invalid checksum" do
      subject.isbn = "0-13-235088-3"
      expect(subject).not_to be_valid
      expect(subject.errors[:isbn]).to include "doesn't appear to be a valid ISBN. Please check the number and try again"
    end

    it "rejects ISBN-10 with X in wrong position" do
      subject.isbn = "0X39420890"
      expect(subject).not_to be_valid
      expect(subject.errors[:isbn]).to include "doesn't appear to be a valid ISBN. Please check the number and try again"
    end
  end

  context "general validation" do
    it "allows ISBN to be blank" do
      subject.isbn = nil
      expect(subject).to be_valid
    end

    it "allows empty string" do
      subject.isbn = ""
      expect(subject).to be_valid
    end

    it "rejects invalid ISBN with less than 10 digits" do
      subject.isbn = "979-8-8917"
      expect(subject).not_to be_valid
      expect(subject.errors[:isbn]).to include "doesn't appear to be a valid ISBN. Please check the number and try again"
    end

    it "rejects invalid ISBN with 11 or 12 digits" do
      subject.isbn = "97989170497"
      expect(subject).not_to be_valid
      expect(subject.errors[:isbn]).to include "doesn't appear to be a valid ISBN. Please check the number and try again"
    end

    it "rejects ISBN with more than 13 digits" do
      subject.isbn = "979-8-89170-497-8-1"
      expect(subject).not_to be_valid
      expect(subject.errors[:isbn]).to include "doesn't appear to be a valid ISBN. Please check the number and try again"
    end

    it "rejects ISBN with letters (except X at end of ISBN-10)" do
      subject.isbn = "979-8-ABCDE-497-8"
      expect(subject).not_to be_valid
      expect(subject.errors[:isbn]).to include "doesn't appear to be a valid ISBN. Please check the number and try again"
    end
  end
end
